config/routes.rb
Rails.application.routes.draw do
  get 'share/:user_id/books', to: "share#books"
  get 'share/:user_id/articles', to: "share#articles"
  get 'share/:user_id/movies', to: "share#movies"
  get 'share/:user_id/tvshows', to: "share#tvshows"
  get 'share/:user_id/podcasts', to: "share#podcasts"


  resources :podcasts do
    collection do
      get 'filter'
    end
  end
  resources :tvshows do
    collection do
      get 'filter'
    end
  end
  resources :articles do
    collection do 
      get 'filter'
    end
  end
  resources :movies do
    collection do
      get 'filter'
    end
  end
  resources :books do
    collection do
      get 'filter'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'signin', to: "sessions#index"
  post 'signin', to: "sessions#create"
  delete 'signin', to: "sessions#destroy"

  get 'signup', to: "users#new"
  post 'signup', to: "users#create"
  get 'account', to: "users#index"
  get 'account/edit', to:"users#edit"
  patch 'account/edit', to: "users#update", as: :update_password

  get 'reset_password', to: "password_resets#index"
  post 'reset_password', to: "password_resets#create"
  get 'reset_password/edit', to: "password_resets#edit"
  patch 'reset_password/edit', to: "password_resets#update"

  get "home", to: "items#index"
  get "add", to: "items#new"
  post "add", to: "items#create"
  
  # Defines the root path route ("/")
  root "sessions#index"
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :require_user_logged_in!

  # GET /articles or /articles.json
  def index
    session['filters'] = {}
    @articles = Current.user.articles.all
  end

  # GET /articles/filter
  def filter
    session['filters'] = {} if session['filters'].blank?
    session['filters'].merge!(filter_params)
    
    @articles = Current.user.articles.all
    @articles = @articles.where("title like ?", "%#{session['filters']['search']}%").or(@articles.where("author like ?", "%#{session['filters']['search']}%")) if session['filters']['search']
    @articles = @articles.where(consumed: session['filters']['show_consumed']) if session['filters']['show_consumed'].present?
    @articles = @articles.where(starred: session['filters']['show_starred']) if session['filters']['show_starred'].present?
    
    render :index
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Current.user.articles.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Current.user.articles.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to articles_url }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    @articles = Current.user.articles.where(consumed:false)
    respond_to do |format|
      if @article.update(article_params)
          format.turbo_stream 
          format.html { redirect_to article_url(@article) }
          format.json { render :show, status: :ok, location: @article }
         
        
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Current.user.articles.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :author, :url, :notes, :starred, :consumed)
    end

    def filter_params
      params.permit(:show_consumed, :show_starred, :search)
    end

    
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<%= turbo_frame_tag article, class: "contents" do %>
  <%= conditional_link_to !sharing, article_path(article.id),"break-words pr-3 py-3 border-t-2 border-gray-30" do %>
    <span class="text-xs md:text-sm lg:text-base"><%=article.created_at.in_time_zone("Eastern Time (US & Canada)").strftime("%m/%d/%Y")%></span>
  <% end %>
  <%= conditional_link_to !sharing, article_path(article.id), "break-words pr-3 py-3 border-t-2 border-gray-300" do %>
    <span class="text-xs md:text-sm lg:text-base"><%=truncate(article.title, length: 25)%></span>
  <% end %>
  <%= conditional_link_to !sharing, article_path(article.id), "break-words pr-3 py-3 border-t-2 border-gray-300" do %>
    <span class="text-xs md:text-sm lg:text-base"><%=article.author%></span>
  <% end %>
  <%= link_to article.url, target: "_blank", class: "break-words pr-3 py-3 border-t-2 border-gray-300 underline hover:text-blue-500" do %>
    <span class="text-xs md:text-sm lg:text-base"><%=truncate(article.url, length: 18)%></span>
  <% end %>
  <%= form_with(model: article, class: "py-3 border-t-2 border-gray-300") do |form| %>
    <%= form.check_box :consumed, { value: !article.consumed, onchange: 'this.form.requestSubmit()' }%>
  <% end %>
          
  <%= button_to article_path(article.id, article: {starred: !article.starred}), method: :patch, form_class: "py-3 border-t-2 border-gray-300" do %>
    <% if article.starred %>
      <i class='ml-4 fa-solid fa-star fa-lg text-yellow-500'></i>
    <% else %>
      <i class="ml-4 fa-regular fa-star fa-lg text-yellow-500"></i>
    <% end %>
  <% end %>       
<% end %>

app/views/articles/_articles.html.erb
  <%= turbo_frame_tag "articles", class: "contents" do %>
  <div id="articles" class="grid grid-cols-6 lg:w-2/3 mt-4 lg:mt-6 lg:mx-auto">
    <div class="border-t-2 border-gray-300 py-2">
      <span class="font-bold text-sm md:text-base lg:text-xl">Date Added</span>
    </div>
    <div class="border-t-2 border-gray-300 py-2">
      <span class="font-bold text-sm md:text-base lg:text-xl">Title</span>
    </div>
    <div class="border-t-2 border-gray-300 py-2"> 
      <span class="font-bold text-sm md:text-base lg:text-xl">Author</span>
    </div>
    <div class="border-t-2 border-gray-300 py-2"> 
      <span class="font-bold text-sm md:text-base lg:text-xl">Link</span>
    </div>
    <div class="border-t-2 border-gray-300 py-2">
      <span class="font-bold text-sm md:text-base lg:text-xl">Read?</span>
    </div>
    <div class="border-t-2 border-gray-300 py-2">  
    </div>
    <%= render articles, sharing: sharing %>
    
</div>
  <% end %>

app/views/articles/_form.html.erb
<%= turbo_frame_tag "add_form", class: "contents" do %>
<%= form_with(model: article, class: "contents", format: :html) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, disabled: viewing, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :author %>
    <%= form.text_field :author, disabled: viewing, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :url %>
    <%= form.text_field :url, disabled: viewing, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :notes %>
    <%= form.text_area :notes, rows: 4, disabled: viewing, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :starred %>
    <%= form.check_box :starred, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label "Read?" %>
    <%= form.check_box :consumed, disabled: viewing, class: "block mt-2 h-5 w-5" %>
  </div>

  <% unless viewing %>
  <% if source == 'new' %>
     <div class="inline">
        <%= form.submit "Add article", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer", data: {turbo_frame: "_top"} %>
      </div>
  <% elsif source == 'edit' %>
      <div class="inline">
        <%= form.submit "Confirm", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
      </div>
  <% end %>
  <% end %>
<% end %>
<% end %>

app/views/articles/edit.html.erb
<div class="mx-auto md:w-2/3 w-full mt-20">
  

  <%= render "form", article: @article, viewing: false, source: "edit" %>

  <%= link_to "Back to articles", articles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/articles/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex items-center">
    <h1 class="font-bold text-4xl m-auto mt-20">Articles</h1>
  </div>

  <div class="flex items-center justify-between w-full lg:w-2/3 lg:mx-auto mt-6 lg:mt-10">
    <%= link_to 'Add article', new_article_path, target: "_top", class: "text-center w-32 rounded-lg py-3 px-5 bg-blue-700 text-white block font-medium hover:opacity-70" %>
    <button class="text-center w-28 rounded-lg py-2 px-3 border-gray-100 block text-sm font-medium hover:opacity-70" data-controller= "share" data-action="click->share#copy" data-share-user-item= "<%= Current.user.id %>/articles" data-share-target="button">Share</button>
  </div>

  <div id="tooltip" class="hidden bg-gray-800 text-white px-4 py-2 rounded text-xs">Copied!</div>

  <% if @articles.length > 0 %>
    <div class="flex flex-col-reverse lg:flex-row lg:w-2/3 lg:mx-auto mt-6">
      <%= form_with url: filter_articles_path, method: :get, data: {controller: "search-form", search_form_target: "form", turbo_frame: "articles"} do |form| %>
        <%= form.text_field :search, placeholder: "Search...", class: "rounded-lg w-full lg:w-auto lg:mr-4", data: {action: "input->search-form#search"} %>
      <% end %>
      <div class="flex mb-3">
        <%= form_with url: filter_articles_path, method: :get, data: {turbo_frame: "articles"}, class: "mr-4" do |form| %>
          <%= form.label "Starred:" %>
          <%= form.select :show_starred, [["All", nil], ["Starred Only", 1], ["Not Starred Only", 0]],  {}, {onchange: "this.form.requestSubmit()", class: "rounded-lg text-sm lg:text-base"} %>
        <% end %>

        <%= form_with url: filter_articles_path, method: :get, data: {turbo_frame: "articles"} do |form| %>
          <%= form.label "Read:" %>
          <%= form.select :show_consumed, [["All", nil], ["Read Only", 1], ["Unread Only", 0]], {}, {onchange: "this.form.requestSubmit()", class: "w-42 rounded-lg text-sm lg:text-base"} %>
        <% end %>
      </div>
    </div>
  <%= render partial: "articles", locals: {articles: @articles, sharing: false} %>

  <% else %>
      <div class="w-full text-center mt-4">
        <span class="italic text-gray-500">You don't have any articles yet. Click "Add Articles" to start your library!</span>
      </div>  
  <% end %>
</div>

app/views/articles/new.html.erb
<div class="mx-auto md:w-2/3 w-full mt-20">
  <h1 class="font-bold text-4xl mt-4">New article</h1>

  <%= render "form", article: @article, viewing: false, source: "new"  %>

  <%= link_to 'Back to articles', articles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium hover:opacity-70" %>
</div>

app/views/articles/show.html.erb
<div class="mx-auto md:w-2/3 w-full mt-20">
  
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render "form", article: @article, viewing: true, source: "show" %>

  <div class="flex justify-between">
  <div class="flex flex-wrap">
    <%= link_to 'Edit', edit_article_path(@article), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium hover:opacity-70" %>
    <div class="inline-block ml-2">
      <%= button_to 'Delete', article_path(@article), method: :delete, class: "bg-red-500 mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium hover:opacity-70" %>
    </div>
    </div>
    <%= link_to 'Back to articles', articles_path, class: "mt-2 ml-2 rounded-lg py-3 px-4 bg-gray-100 inline-block font-medium hover:opacity-70" %>
 </div>
</div>

app/views/articles/update.turbo_stream.erb
<%= turbo_stream.replace @article do %>
    <%= render @article, sharing: false %>
<% end %>

<%= turbo_stream.replace "unread_articles" do %>
     <%= turbo_frame_tag "unread_articles" do %>
        <% if @articles.length > 0 %>
            <div class="w-2/3 mx-auto mt-4">
                <h2 class="font-bold text-2xl">Articles</h2>
            </div>
            <%= render partial: "articles/articles", locals: {articles: @articles, sharing: false} %>
        <% end %>
    <% end %>
<% end %>