config/routes.rb
Rails.application.routes.draw do
  get 'share/:user_id/books', to: "share#books"
  get 'share/:user_id/articles', to: "share#articles"
  get 'share/:user_id/movies', to: "share#movies"
  get 'share/:user_id/tvshows', to: "share#tvshows"
  get 'share/:user_id/podcasts', to: "share#podcasts"


  resources :podcasts do
    collection do
      get 'filter'
    end
  end
  resources :tvshows do
    collection do
      get 'filter'
    end
  end
  resources :articles do
    collection do 
      get 'filter'
    end
  end
  resources :movies do
    collection do
      get 'filter'
    end
  end
  resources :books do
    collection do
      get 'filter'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'signin', to: "sessions#index"
  post 'signin', to: "sessions#create"
  delete 'signin', to: "sessions#destroy"

  get 'signup', to: "users#new"
  post 'signup', to: "users#create"
  get 'account', to: "users#index"
  get 'account/edit', to:"users#edit"
  patch 'account/edit', to: "users#update", as: :update_password

  get 'reset_password', to: "password_resets#index"
  post 'reset_password', to: "password_resets#create"
  get 'reset_password/edit', to: "password_resets#edit"
  patch 'reset_password/edit', to: "password_resets#update"

  get "home", to: "items#index"
  get "add", to: "items#new"
  post "add", to: "items#create"
  
  # Defines the root path route ("/")
  root "sessions#index"
end

app/models/tvshow.rb
class Tvshow < ApplicationRecord
  belongs_to :user
end

app/controllers/tvshows_controller.rb
class TvshowsController < ApplicationController
  before_action :set_tvshow, only: %i[ show edit update destroy ]
  before_action :require_user_logged_in!

  # GET /tvshows or /tvshows.json
  def index
    session['filters'] = {}
    @tvshows = Current.user.tvshows.all
  end

  # GET /tvshows/filter
  def filter
    session['filters'] = {} if session['filters'].blank?
    session['filters'].merge!(filter_params)
    
    @tvshows = Current.user.tvshows.all
    @tvshows = @tvshows.where("name like ?", "%#{session['filters']['search']}%") if session['filters']['search']
    @tvshows = @tvshows.where(consumed: session['filters']['show_consumed']) if session['filters']['show_consumed'].present?
    @tvshows = @tvshows.where(starred: session['filters']['show_starred']) if session['filters']['show_starred'].present?
    
    render :index
  end

  # GET /tvshows/1 or /tvshows/1.json
  def show
  end

  # GET /tvshows/new
  def new
    @tvshow = Current.user.tvshows.new
  end

  # GET /tvshows/1/edit
  def edit
  end

  # POST /tvshows or /tvshows.json
  def create
    @tvshow = Current.user.tvshows.new(tvshow_params)

    respond_to do |format|
      if @tvshow.save
        format.html { redirect_to tvshows_url }
        format.json { render :show, status: :created, location: @tvshow }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tvshow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tvshows/1 or /tvshows/1.json
  def update
    
    respond_to do |format|
      if @tvshow.update(tvshow_params)
          @tvshows = Current.user.tvshows.where(consumed: false)
          #binding.pry
          format.turbo_stream 
          format.html { redirect_to tvshow_url(@tvshow) }
          format.json { render :show, status: :ok, location: @tvshow }
         
        
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tvshow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tvshows/1 or /tvshows/1.json
  def destroy
    @tvshow.destroy

    respond_to do |format|
      format.html { redirect_to tvshows_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tvshow
      @tvshow = Current.user.tvshows.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tvshow_params
      params.require(:tvshow).permit(:name, :notes, :starred, :consumed)
    end

    def filter_params
      params.permit(:show_consumed, :show_starred, :search)
    end

    
end

app/helpers/tvshows_helper.rb
module TvshowsHelper
end

app/views/tvshows/_form.html.erb
<%= turbo_frame_tag "add_form", class: "contents" do %>
<%= form_with(model: tvshow, class: "contents", format: :html) do |form| %>
  <% if tvshow.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(tvshow.errors.count, "error") %> prohibited this tvshow from being saved:</h2>

      <ul>
        <% tvshow.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, disabled: viewing, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :notes %>
    <%= form.text_area :notes, rows: 4, disabled: viewing, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :starred %>
    <%= form.check_box :starred, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label "Watched?" %>
    <%= form.check_box :consumed, disabled: viewing, class: "block mt-2 h-5 w-5" %>
  </div>

  <% unless viewing %>
  <% if source == 'new' %>
     <div class="inline">
        <%= form.submit "Add TV Show", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer", data: {turbo_frame: "_top"} %>
      </div>
  <% elsif source == 'edit' %>
      <div class="inline">
        <%= form.submit "Confirm", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
      </div>
  <% end %>
  <% end %>
<% end %>
<% end %>

app/views/tvshows/_tvshow.html.erb
<%= turbo_frame_tag tvshow, class: "contents" do %>
       
          <%= conditional_link_to !sharing, tvshow_path(tvshow.id), "break-words py-3 border-t-2 border-gray-300" do %>
            <span class="text-sm lg:text-base"><%=tvshow.created_at.in_time_zone("Eastern Time (US & Canada)").strftime("%m/%d/%Y")%></span>
          <% end %>
          <%= conditional_link_to !sharing, tvshow_path(tvshow.id), "break-words pr-3 py-3 border-t-2 border-gray-300" do %>
            <span class="text-sm lg:text-base"><%=tvshow.name%></span>
          <% end %>
        
            <%= form_with(model: tvshow, class: "py-3 border-t-2 border-gray-300") do |form| %>
            <%= form.check_box :consumed, { value: !tvshow.consumed, onchange: 'this.form.requestSubmit()', disabled: sharing }%>
            <% end %>
          
            <%= button_to tvshow_path(tvshow.id, tvshow: {starred: !tvshow.starred}), method: :patch, form_class: "py-3 border-t-2 border-gray-300", disabled: sharing do %>
              <% if tvshow.starred %>
                <i class='fa-solid fa-star fa-lg text-yellow-500 ml-4'></i>
              <% else %>
                <i class="fa-regular fa-star fa-lg text-yellow-500 ml-4"></i>
              <% end %>
            <% end %>
              
<% end %>
  

app/views/tvshows/_tvshows.html.erb
 <%= turbo_frame_tag "tvshows", class: "contents" do %>
  <div id="tvshows" class="grid grid-cols-4 lg:w-2/3 mt-4 lg:mt-6 lg:mx-auto">
   
      <div class="border-t-2 border-gray-300 py-2">
        <span class="font-bold text-lg lg:text-xl">Date Added</span>
      </div>
     <div class="border-t-2 border-gray-300 py-2">
        <span class="font-bold text-lg lg:text-xl">Name</span>
      </div>
      <div class="border-t-2 border-gray-300 py-2">
        <span class="font-bold text-lg lg:text-xl">Watched?</span>
      </div>
     <div class="border-t-2 border-gray-300 py-2">
        
      </div>
        <%= render tvshows, sharing: sharing %>
    
      </div>
  <% end %>

app/views/tvshows/edit.html.erb
<div class="mx-auto md:w-2/3 w-full mt-20">
  

  <%= render "form", tvshow: @tvshow, viewing: false, source: "edit" %>

  <%= link_to "Back to tvshows", tvshows_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tvshows/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex items-center">
    <h1 class="font-bold text-4xl m-auto mt-20">TV Shows</h1>
    
  </div>

  <div class="flex items-center justify-between w-full lg:w-2/3 lg:mx-auto mt-6 lg:mt-10">
    <%= link_to 'Add TV Show', new_tvshow_path, class: "text-center w-36 rounded-lg py-3 px-5 bg-blue-700 text-white block font-medium hover:opacity-70" %>
    <button class="text-center w-28 rounded-lg py-2 px-3 border-gray-100 block text-sm font-medium hover:opacity-70" data-controller= "share" data-action="click->share#copy" data-share-user-item= "<%= Current.user.id %>/tvshows" data-share-target="button">Share</button>
  </div>
   <div id="tooltip" class="hidden bg-gray-800 text-white px-4 py-2 rounded text-xs">Copied!</div>

  <% if @tvshows.length > 0 %>
    <div class="flex flex-col-reverse lg:flex-row lg:w-2/3 lg:mx-auto mt-6">
      <%= form_with url: filter_tvshows_path, method: :get, data: {controller: "search-form", search_form_target: "form", turbo_frame: "tvshows"} do |form| %>
        <%= form.text_field :search, placeholder: "Search...", class: "rounded-lg w-full lg:w-auto lg:mr-4", data: {action: "input->search-form#search"} %>
      <% end %>
    <div class="flex mb-3">
      <%= form_with url: filter_tvshows_path, method: :get, data: {turbo_frame: "tvshows"}, class: "mr-4" do |form| %>
        <%= form.label "Starred:", class: "text-sm lg:text-base" %>
        <%= form.select :show_starred, [["All", nil], ["Starred Only", 1], ["Not Starred Only", 0]],  {}, {onchange: "this.form.requestSubmit()", class: "rounded-lg text-sm lg:text-base"} %>
      <% end %>

      <%= form_with url: filter_tvshows_path, method: :get, data: {turbo_frame: "tvshows"} do |form| %>
        <%= form.label "Watched:", class: "text-sm lg:text-base" %>
        <%= form.select :show_consumed, [["All", nil], ["Watched Only", 1], ["Unwatched Only", 0]], {}, {onchange: "this.form.requestSubmit()", class: "w-42 rounded-lg text-sm lg:text-base"} %>
      <% end %>
  </div>
</div>
 <%= render partial: "tvshows", locals: {tvshows: @tvshows, sharing: false} %>

 <% else %>
  <div class="w-full text-center mt-4">
    <span class="italic text-gray-500">You don't have any TV shows yet. Click "Add TV Show" to start your library!</span>
  </div> 
<% end %>
</div>

app/views/tvshows/new.html.erb
<div class="mx-auto md:w-2/3 w-full mt-20">
  <h1 class="font-bold text-4xl mt-4">New TV Show</h1>

  <%= render "form", tvshow: @tvshow, viewing: false, source: "new"  %>

  <%= link_to 'Back to TV Shows', tvshows_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block w-auto font-medium hover:opacity-70" %>
</div>

app/views/tvshows/show.html.erb
<div class="mx-auto md:w-2/3 w-full mt-20">
  
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render "form", tvshow: @tvshow, viewing: true, source: "show" %>

  <div class="flex justify-between">
  <div class="flex flex-wrap">
    <%= link_to 'Edit', edit_tvshow_path(@tvshow), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium hover:opacity-70" %>
    <div class="inline-block ml-2">
      <%= button_to 'Delete', tvshow_path(@tvshow), method: :delete, class: "bg-red-500 mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium hover:opacity-70" %>
    </div>
    </div>
    <%= link_to 'Back to TV Shows', tvshows_path, class: "mt-2 ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium hover:opacity-70" %>
 </div>
</div>

app/views/tvshows/update.turbo_stream.erb
<%= turbo_stream.replace @tvshow do %>
    <%= render @tvshow, sharing: false %>
<% end %>

<%= turbo_stream.replace "unwatched_tvshows" do %>
     <%= turbo_frame_tag "unwatched_tvshows" do %>
        <% if @tvshows.length > 0 %>
        <div class="w-2/3 mx-auto mt-4">
            <h2 class="font-bold text-2xl">TV Shows</h2>
        </div>
        <%= render partial: "tvshows/tvshows", locals: {tvshows: @tvshows, sharing: false} %>
        <% end %>
    <% end %>
<% end %>