config/routes.rb
Rails.application.routes.draw do
  get 'share/:user_id/books', to: "share#books"
  get 'share/:user_id/articles', to: "share#articles"
  get 'share/:user_id/movies', to: "share#movies"
  get 'share/:user_id/tvshows', to: "share#tvshows"
  get 'share/:user_id/podcasts', to: "share#podcasts"


  resources :podcasts do
    collection do
      get 'filter'
    end
  end
  resources :tvshows do
    collection do
      get 'filter'
    end
  end
  resources :articles do
    collection do 
      get 'filter'
    end
  end
  resources :movies do
    collection do
      get 'filter'
    end
  end
  resources :books do
    collection do
      get 'filter'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'signin', to: "sessions#index"
  post 'signin', to: "sessions#create"
  delete 'signin', to: "sessions#destroy"

  get 'signup', to: "users#new"
  post 'signup', to: "users#create"
  get 'account', to: "users#index"
  get 'account/edit', to:"users#edit"
  patch 'account/edit', to: "users#update", as: :update_password

  get 'reset_password', to: "password_resets#index"
  post 'reset_password', to: "password_resets#create"
  get 'reset_password/edit', to: "password_resets#edit"
  patch 'reset_password/edit', to: "password_resets#update"

  get "home", to: "items#index"
  get "add", to: "items#new"
  post "add", to: "items#create"
  
  # Defines the root path route ("/")
  root "sessions#index"
end

app/views/shared/_flash.html.erb
<% unless Current.user.present? %>

    <% if flash[:notice]%>
        <div class="mt-20 bg-green-200 text-green-900 p-4 w-96" role="alert">
            <p><%= flash[:notice] %></p>
        </div>
    <% end %>

    <% if flash[:alert]%>
        <div class="mt-20 bg-red-200 text-red-800 p-4 w-96 m-0" role="alert">
            <p><%= flash[:alert] %></p>
        </div>
    <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="w-full flex items-center justify-between flex-wrap bg-blue-800 p-6 fixed top-0" data-controller="navbar">
<div class="w-full flex flex-col lg:flex-row">
  <div class="w-full lg:w-auto flex justify-between flex-row ">
     <div class="flex items-center flex-shrink-0 text-white mr-6">
        <%= link_to "Personal Library", root_path, class: "font-semibold text-xl tracking-tight" %>
     </div>
  <div class="lg:hidden flex-grow items-center">
    <%= link_to add_path, class: "ml-3 inline-block text-white bg-blue-300 p-3 rounded cursor-pointer hover:opacity-70" do %>
      <i class="fa-solid fa-plus"></i>
    <% end %>
  </div>
  <div class="lg:hidden" data-navbar-target= "button" >
       <button type="button" class="inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
         <i class="fa-solid fa-bars fa-xl" id="open-btn" data-action="click->navbar#open"></i>
        </button>
  </div>
  </div>
      
    <% if Current.user %>
    <div class="hidden lg:flex w-auto flex-grow items-center">
      <div class="text-sm flex-grow">
        <%= link_to "Books", books_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4" %>
        <%= link_to "Articles", articles_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4"%>
        <%= link_to "Movies", movies_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4"%>
        <%= link_to "TV Shows", tvshows_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4"%>
        <%= link_to "Podcasts", podcasts_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4" %>
        <%= link_to add_path, class: "ml-3 inline-block text-white bg-blue-300 p-3 rounded cursor-pointer hover:opacity-70" do %>
          <i class="fa-solid fa-plus"></i>
        <% end %>
      </div>
      
      
      <div class="w-auto flex items-center">
        <%= link_to "Account", account_path, class: "block lg:inline-block text-gray-200 hover:text-white"%>
        <%= button_to "Log out", signin_path, method: :delete, class: "ml-3 block lg:inline-block text-white text-sm bg-red-500 p-2 rounded font-medium cursor-pointer hover:opacity-70"%>
      </div>
    </div>

    <div class="hidden lg:hidden" data-navbar-target="menu">
      <div class="flex flex-col w-auto">
        <%= link_to "Books", books_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4" %>
        <%= link_to "Articles", articles_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4"%>
        <%= link_to "Movies", movies_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4"%>
        <%= link_to "TV Shows", tvshows_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4"%>
        <%= link_to "Podcasts", podcasts_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4" %>
        <%= link_to "Account", account_path, class: "block mt-4 lg:inline-block text-gray-200 hover:text-white"%>
        <%= button_to "Log out", signin_path, method: :delete, class: "mt-4 block text-white text-sm bg-red-500 p-2 rounded font-medium cursor-pointer hover:opacity-70"%>
      </div>
    </div>
    <% end %>
    </div>
</nav>