config/routes.rb
Rails.application.routes.draw do
  get 'share/:user_id/books', to: "share#books"
  get 'share/:user_id/articles', to: "share#articles"
  get 'share/:user_id/movies', to: "share#movies"
  get 'share/:user_id/tvshows', to: "share#tvshows"
  get 'share/:user_id/podcasts', to: "share#podcasts"


  resources :podcasts do
    collection do
      get 'filter'
    end
  end
  resources :tvshows do
    collection do
      get 'filter'
    end
  end
  resources :articles do
    collection do 
      get 'filter'
    end
  end
  resources :movies do
    collection do
      get 'filter'
    end
  end
  resources :books do
    collection do
      get 'filter'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'signin', to: "sessions#index"
  post 'signin', to: "sessions#create"
  delete 'signin', to: "sessions#destroy"

  get 'signup', to: "users#new"
  post 'signup', to: "users#create"
  get 'account', to: "users#index"
  get 'account/edit', to:"users#edit"
  patch 'account/edit', to: "users#update", as: :update_password

  get 'reset_password', to: "password_resets#index"
  post 'reset_password', to: "password_resets#create"
  get 'reset_password/edit', to: "password_resets#edit"
  patch 'reset_password/edit', to: "password_resets#update"

  get "home", to: "items#index"
  get "add", to: "items#new"
  post "add", to: "items#create"
  
  # Defines the root path route ("/")
  root "sessions#index"
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  belongs_to :user
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :set_podcast, only: %i[ show edit update destroy ]
  before_action :require_user_logged_in!

  # GET /podcasts or /podcasts.json
  def index
    session['filters'] = {}
    @podcasts = Current.user.podcasts.all
  end

  # GET /podcasts/filter
  def filter
    session['filters'] = {} if session['filters'].blank?
    session['filters'].merge!(filter_params)
    
    @podcasts = Current.user.podcasts.all
    @podcasts = @podcasts.where("title like ?", "%#{session['filters']['search']}%").or(@podcasts.where("podcast like ?", "%#{session['filters']['search']}%")) if session['filters']['search']
    @podcasts = @podcasts.where(consumed: session['filters']['show_consumed']) if session['filters']['show_consumed'].present?
    @podcasts = @podcasts.where(starred: session['filters']['show_starred']) if session['filters']['show_starred'].present?
    
    render :index
  end

  # GET /podcasts/1 or /podcasts/1.json
  def show
  end

  # GET /podcasts/new
  def new
    @podcast = Current.user.podcasts.new
  end

  # GET /podcasts/1/edit
  def edit
  end

  # POST /podcasts or /podcasts.json
  def create
    @podcast = Current.user.podcasts.new(podcast_params)

    respond_to do |format|
      if @podcast.save
        format.html { redirect_to podcasts_url }
        format.json { render :show, status: :created, location: @podcast }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /podcasts/1 or /podcasts/1.json
  def update
    respond_to do |format|
      if @podcast.update(podcast_params)
          @podcasts = Current.user.podcasts.where(consumed: false)
          format.turbo_stream 
          format.html { redirect_to podcast_url(@podcast) }
          format.json { render :show, status: :ok, location: @podcast }
         
        
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /podcasts/1 or /podcasts/1.json
  def destroy
    @podcast.destroy

    respond_to do |format|
      format.html { redirect_to podcasts_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_podcast
      @podcast = Current.user.podcasts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def podcast_params
      params.require(:podcast).permit(:name, :podcast, :url, :notes, :starred, :consumed)
    end

    def filter_params
      params.permit(:show_consumed, :show_starred, :search)
    end

    
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
   
end

app/views/podcasts/_form.html.erb
<%= turbo_frame_tag "add_form", class: "contents" do %>
<%= form_with(model: podcast, class: "contents", format: :html) do |form| %>
  <% if podcast.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(podcast.errors.count, "error") %> prohibited this podcast from being saved:</h2>

      <ul>
        <% podcast.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, disabled: viewing, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :podcast %>
    <%= form.text_field :podcast, disabled: viewing, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :url %>
    <%= form.text_field :url, disabled: viewing, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :notes %>
    <%= form.text_area :notes, rows: 4, disabled: viewing, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :starred %>
    <%= form.check_box :starred, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label "Completed?" %>
    <%= form.check_box :consumed, disabled: viewing, class: "block mt-2 h-5 w-5" %>
  </div>

  <% unless viewing %>
  <% if source == 'new' %>
     <div class="inline">
        <%= form.submit "Add podcast", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer", data: {turbo_frame: "_top"} %>
      </div>
  <% elsif source == 'edit' %>
      <div class="inline">
        <%= form.submit "Confirm", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
      </div>
  <% end %>
  <% end %>
<% end %>
<% end %>

app/views/podcasts/_podcast.html.erb
<%= turbo_frame_tag podcast, class: "contents" do %>
          
          <%= conditional_link_to !sharing, podcast_path(podcast.id), "break-words pr-3 py-3 border-t-2 border-gray-300" do %>
            <span class="text-sm lg:text-base"><%=podcast.created_at.in_time_zone("Eastern Time (US & Canada)").strftime("%m/%d/%Y")%></span>
          <% end %>
          
          <%= conditional_link_to !sharing, podcast_path(podcast.id), "break-words pr-3 py-3 border-t-2 border-gray-300" do %>
            <span class="text-sm lg:text-base"><%=podcast.name%></span>
          <% end %>
          <%= conditional_link_to !sharing, podcast_path(podcast.id), "break-words pr-3 py-3 border-t-2 border-gray-300" do %>
            <span class="text-sm lg:text-base"><%=podcast.podcast%></span>
          <% end %>
          <%= link_to podcast.url, target: "_blank", class: "break-words pr-3 py-3 border-t-2 border-gray-300 underline hover:text-blue-500" do %>
            <span class="text-sm lg:text-base"><%=truncate(podcast.url, length: 18)%></span>
          <% end %>
            <%= form_with(model: podcast, class: "py-3 border-t-2 border-gray-300") do |form| %>
            <%= form.check_box :consumed, { value: !podcast.consumed, onchange: 'this.form.requestSubmit()', disabled: sharing }%>
            <% end %>
          
            <%= button_to podcast_path(podcast.id, podcast: {starred: !podcast.starred}), method: :patch, form_class: "py-3 border-t-2 border-gray-300", disabled: sharing do %>
              <% if podcast.starred %>
                <i class='fa-solid fa-star fa-lg text-yellow-500'></i>
              <% else %>
                <i class="fa-regular fa-star fa-lg text-yellow-500"></i>
              <% end %>
            <% end %>
              
<% end %>
  

app/views/podcasts/_podcasts.html.erb
  <%= turbo_frame_tag "podcasts", class: "contents" do %>
  <div id="podcasts" class="grid grid-cols-6 lg:w-2/3 mt-4 lg:mt-6 lg:mx-auto">
   
      <div class="border-t-2 border-gray-300 py-2">
        <span class="font-bold text-xs lg:text-xl">Date Added</span>
      </div>
     <div class="border-t-2 border-gray-300 py-2">
        <span class="font-bold text-xs lg:text-xl">Name</span>
      </div>
      <div class="border-t-2 border-gray-300 py-2"> 
        <span class="font-bold text-xs lg:text-xl">Podcast</span>
      </div>
      <div class="border-t-2 border-gray-300 py-2"> 
        <span class="font-bold text-xs lg:text-xl">Link</span>
      </div>
      <div class="border-t-2 border-gray-300 py-2">
        <span class="font-bold text-xs lg:text-xl">Finished?</span>
      </div>
     <div class="border-t-2 border-gray-300 py-2">
        
      </div>
        <%= render podcasts, sharing: sharing %>
    
      </div>
  <% end %>

app/views/podcasts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full mt-20">
  

  <%= render "form", podcast: @podcast, viewing: false, source: "edit" %>

  <%= link_to "Back to podcasts", podcasts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/podcasts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex items-center">
    <h1 class="font-bold text-4xl m-auto mt-20">Podcasts</h1>
    
  </div>

  <div class="flex items-center justify-between w-full lg:w-2/3 lg:mx-auto mt-6 lg:mt-10">
    <%= link_to 'Add podcast', new_podcast_path, target: "_top", class: "text-center w-36 rounded-lg py-3 px-5 bg-blue-700 text-white block font-medium hover:opacity-70" %>
    <button class="text-center w-28 rounded-lg py-2 px-3 border-gray-100 block text-sm font-medium hover:opacity-70" data-controller= "share" data-action="click->share#copy" data-share-user-item= "<%= Current.user.id %>/podcasts" data-share-target="button">Share</button>
  </div>
   <div id="tooltip" class="hidden bg-gray-800 text-white px-4 py-2 rounded text-xs">Copied!</div>

  <% if @podcasts.length > 0 %>
    <div class="flex flex-col-reverse lg:flex-row lg:w-2/3 lg:mx-auto mt-6">
      <%= form_with url: filter_podcasts_path, method: :get, data: {controller: "search-form", search_form_target: "form", turbo_frame: "podcasts"} do |form| %>
        <%= form.text_field :search, placeholder: "Search...", class: "rounded-lg w-full lg:w-auto lg:mr-4", data: {action: "input->search-form#search"} %>
      <% end %>
      <div class="flex mb-3">
        <%= form_with url: filter_podcasts_path, method: :get, data: {turbo_frame: "podcasts"}, class: "mr-4" do |form| %>
          <%= form.label "Starred:", class: "text-sm lg:text-base" %>
          <%= form.select :show_starred, [["All", nil], ["Starred Only", 1], ["Not Starred Only", 0]],  {}, {onchange: "this.form.requestSubmit()", class: "rounded-lg text-sm lg:text-base"} %>
        <% end %>
        <%= form_with url: filter_podcasts_path, method: :get, data: {turbo_frame: "podcasts"} do |form| %>
          <%= form.label "Finished:", class: "text-sm lg:text-base" %>
          <%= form.select :show_consumed, [["All", nil], ["Finished Only", 1], ["Unfinished Only", 0]], {}, {onchange: "this.form.requestSubmit()", class: "w-42 rounded-lg text-sm lg:text-base"} %>
        <% end %>
    </div>
</div>
  <%= render partial: "podcasts", locals: {podcasts: @podcasts, sharing: false} %>

  <% else %>
    <div class="w-full text-center mt-4">
      <span class="italic text-gray-500">You don't have any podcasts yet. Click "Add Podcast" to start your library!</span>
    </div>  
  <% end %>
</div>

app/views/podcasts/new.html.erb
<div class="mx-auto md:w-2/3 w-full mt-20">
  <h1 class="font-bold text-4xl mt-4">New podcast</h1>

  <%= render "form", podcast: @podcast, viewing: false, source: "new"  %>

  <%= link_to 'Back to podcasts', podcasts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium hover:opacity-70" %>
</div>

app/views/podcasts/show.html.erb
<div class="mx-auto md:w-2/3 w-full mt-20">
  
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render "form", podcast: @podcast, viewing: true, source: "show" %>

  <div class="flex justify-between">
  <div class="flex flex-wrap">
    <%= link_to 'Edit', edit_podcast_path(@podcast), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium hover:opacity-70" %>
    <div class="inline-block ml-2">
      <%= button_to 'Delete', podcast_path(@podcast), method: :delete, class: "bg-red-500 mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium hover:opacity-70" %>
    </div>
    </div>
    <%= link_to 'Back to podcasts', podcasts_path, class: "mt-2 ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium hover:opacity-70" %>
 </div>
</div>

app/views/podcasts/update.turbo_stream.erb
<%= turbo_stream.replace @podcast do %>
    <%= render @podcast, sharing: false %>
<% end %>

<%= turbo_stream.replace "unconsumed_podcasts" do %>
    <%= turbo_frame_tag "unconsumed_podcasts" do %>
        <% if @podcasts.length > 0 %>
        <div class="w-2/3 mx-auto mt-4">
            <h2 class="font-bold text-2xl">Podcasts</h2>
        </div>
        <%= render partial: "podcasts/podcasts", locals: {podcasts: @podcasts, sharing: false} %>
        <% end %>
    <% end %>
<% end %>